"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 6.0.3.
"""
from pathlib import Path
import environ  # ← 1. Импортируем библиотеку

# ← 2. Инициализируем environ ДО всего остального
env = environ.Env(
    # Можно указать типы по умолчанию для переменных
    DEBUG=(bool, False)
)
# Читаем файл .env из корня проекта
environ.Env.read_env(Path(__file__).resolve().parent.parent / '.env')

BASE_DIR = Path(__file__).resolve().parent.parent

# ← 3. Теперь можно безопасно читать переменные
SECRET_KEY = env('SECRET_KEY')  # Без default — ошибка если нет, чтобы не забыть
DEBUG = env('DEBUG', default=True)
TELEGRAM_BOT_TOKEN = env('TELEGRAM_BOT_TOKEN', default='')

# ← 4. Остальные настройки...
ALLOWED_HOSTS = env('ALLOWED_HOSTS', default='*').split(',') if env('ALLOWED_HOSTS', default='') else ['*']


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-xmkz7_8cod4rrkz#70&gfowte%3ut!uqd-9nly2teozfd%8aws'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tracker',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# CELERY_BEAT_SCHEDULE = {
#     'check-prices-every-30-minutes': {
#         'task': 'tracker.tasks.check_prices_task',
#         'schedule': 1800.0, # Проверка каждые 30 минут
#     },
# }

# --- Настройки для Celery (будем использовать позже) ---
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

# --- Токен Telegram бота ---
# TELEGRAM_BOT_TOKEN = ''  # Пока оставь пустым, добавим позже

# === Celery Configuration ===
CELERY_BROKEN_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Europe/Samara'

# Расписание задач
CELERY_BEAT_SCHEDULE = {
    'check-prices-every-30-minutes': {
        'task': 'tracker.tasks.check_all_prices',
        'schedule': 1800.0,
    },
}




# === ОТЛАДКА: удали после проверки ===
import os
print(f"🔍 BASE_DIR: {BASE_DIR}")
print(f"🔍 .env существует: {(BASE_DIR / '.env').exists()}")
if (BASE_DIR / '.env').exists():
    with open(BASE_DIR / '.env', 'r', encoding='utf-8') as f:
        content = f.read()
        print(f"🔍 Содержимое .env:\n{content}")
        if 'TELEGRAM_BOT_TOKEN' in content:
            print("✅ TELEGRAM_BOT_TOKEN найден в файле")
        else:
            print("❌ TELEGRAM_BOT_TOKEN НЕ найден в файле")