# Generated by Django 6.0.3 on 2026-03-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Полная ссылка на страницу товара', max_length=500, verbose_name='ссылка на товар')),
                ('name', models.CharField(blank=True, help_text='Название заполнится автоматически', max_length=255, verbose_name='Название товара')),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, help_text='Цена в рублях', max_digits=10, null=True, verbose_name='Текущая цена')),
                ('target_price', models.DecimalField(decimal_places=2, help_text='При достижении этой цены придет уведомление', max_digits=10, verbose_name='Желаемая цена')),
                ('telegram_id', models.BigIntegerField(blank=True, help_text='ID пользователя для уведомлений', null=True, verbose_name='Telegram ID пользователя')),
                ('is_active', models.BooleanField(default=True, help_text='Если выключено, товар не отслеживается', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
    ]
